//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Example.Domain.Resources.Variables {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppSettings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppSettings() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Example.Domain.Resources.Variables.AppSettings", typeof(AppSettings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 2B692FDA-1B98-4B29-9414-D09645BCBF0E.
        /// </summary>
        internal static string GATEWAY_ID_KEY {
            get {
                return ResourceManager.GetString("GATEWAY_ID_KEY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a GatewayAPIKey.
        /// </summary>
        internal static string HEADER_CODENAME_GATEWAYID_KEY {
            get {
                return ResourceManager.GetString("HEADER_CODENAME_GATEWAYID_KEY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SecurityKeyId.
        /// </summary>
        internal static string HEADER_CODENAME_SECURITYID_KEY {
            get {
                return ResourceManager.GetString("HEADER_CODENAME_SECURITYID_KEY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 1E4F66B8-8602-4F9F-9AAC-F1D329A4AB1D.
        /// </summary>
        internal static string SECURITY_ID_KEY {
            get {
                return ResourceManager.GetString("SECURITY_ID_KEY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 0EBFF1C5-9FFE-4771-ADB6-60B7787F92F2.
        /// </summary>
        internal static string USER_PASSWORD_KEY {
            get {
                return ResourceManager.GetString("USER_PASSWORD_KEY", resourceCulture);
            }
        }
    }
}
